### ISSUE TITLE
esp-adf

### ISSUE THREAD

**Issue by colesnicov** [ctag-fh-kiel/ctag-straempler#9]
Hello.  why don't you use [ESP-ADF](https://github.com/espressif/esp-adf)?

**Comment by ctag-fh-kiel** [comment]
Strämpler was conceived before ADF was published... 
For the use-case of Strämpler, I am unsure what benefits ADF would have, are there any?

**Comment by milkowski** [comment]
For current ESP32 core probably not much (although it has much broader audio format support), but if we were considering upgrade to ESP32-S2/S3 modules with Xtensa X7 cores, that have additional DSP-oriented instructions it would be very beneficial. Also since I see there have been new activity in this project recently, with new hardware design and TBD firmware option, I think it would be great to try to unify Straempler and TBD functionality in new Straempler 2/NX/+/wathever, using those new chips and updated hardware (with buttons and separate gain controls per input channel to create functional superset for cases where TBD controls will be not enough).
I would interested in helping to achieve this goal, since currently I'm in the process of assembling few Straempler and TBD modules for myself.

**Comment by ctag-fh-kiel** [comment]
Absolutely, it would be great to unify both platforms and create better versions. I plan hardware iterations towards autumn/winter this year, as summer is reserved for other things already :)
It would be great to have you onboard! Thanks for the interest and let me know how happy you are with the modules... Cheers:)
